from api.models import Company, Vacancy

company1 = Company.objects.create(name="TechNova", description="Pioneering tech solutions", city="San Francisco", address="1000 Silicon St")
company2 = Company.objects.create(name="EcoGreen", description="Sustainable energy solutions", city="Portland", address="200 Green Rd")
company3 = Company.objects.create(name="Smart Innovations", description="Innovative smart devices", city="Austin", address="300 Innovation Blvd")
company4 = Company.objects.create(name="DataWorks", description="Data analytics and consulting", city="Chicago", address="400 Data Ave")
company5 = Company.objects.create(name="HealthGen", description="Biotech and healthcare research", city="Boston", address="500 Health Park")
company6 = Company.objects.create(name="CyberSecure", description="Cybersecurity services", city="New York", address="600 Security St")
company7 = Company.objects.create(name="GlobalTech", description="Global technology solutions", city="Los Angeles", address="700 Global Way")
company8 = Company.objects.create(name="FutureEnergy", description="Renewable energy innovation", city="Seattle", address="800 Future Blvd")
company9 = Company.objects.create(name="NextGen Enterprises", description="Next-generation products", city="Denver", address="900 Startup Park")
company10 = Company.objects.create(name="LogiTrans", description="Global logistics network", city="Miami", address="1000 Logistics Ln")
company11 = Company.objects.create(name="AutoTech Motors", description="Advanced automotive technologies", city="Detroit", address="1100 Motor Ave")
company12 = Company.objects.create(name="MedCare", description="Healthcare solutions", city="Phoenix", address="1200 Care St")
company13 = Company.objects.create(name="BioFoods", description="Biotechnology in food production", city="Philadelphia", address="1300 Food St")
company14 = Company.objects.create(name="ShopSmart", description="Smart retail solutions", city="Dallas", address="1400 Mall Rd")
company15 = Company.objects.create(name="CleanEnergy", description="Sustainable energy solutions", city="San Diego", address="1500 Solar Blvd")

Vacancy.objects.create(name="Full-Stack Developer", description="Develop web applications", salary=8500, company=company1)
Vacancy.objects.create(name="Sustainability Manager", description="Oversee sustainability projects", salary=9000, company=company2)
Vacancy.objects.create(name="Product Designer", description="Design user-centric products", salary=7800, company=company3)
Vacancy.objects.create(name="Data Analyst", description="Analyze and interpret data", salary=8200, company=company4)
Vacancy.objects.create(name="Medical Researcher", description="Conduct healthcare research", salary=8800, company=company5)
Vacancy.objects.create(name="Network Engineer", description="Design and maintain networks", salary=8500, company=company6)
Vacancy.objects.create(name="Digital Marketing Specialist", description="Develop digital campaigns", salary=7600, company=company7)
Vacancy.objects.create(name="Energy Consultant", description="Advise on renewable energy solutions", salary=9500, company=company8)
Vacancy.objects.create(name="Business Development Specialist", description="Expand business opportunities", salary=8700, company=company9)
Vacancy.objects.create(name="Supply Chain Manager", description="Oversee supply chain operations", salary=8300, company=company10)
Vacancy.objects.create(name="Industrial Engineer", description="Optimize production systems", salary=9100, company=company11)
Vacancy.objects.create(name="Nurse Practitioner", description="Provide medical support", salary=8000, company=company12)
Vacancy.objects.create(name="Quality Control Specialist", description="Ensure product quality", salary=7400, company=company13)
Vacancy.objects.create(name="Retail Operations Manager", description="Manage store operations", salary=7700, company=company14)
Vacancy.objects.create(name="Energy Systems Analyst", description="Analyze energy consumption patterns", salary=8800, company=company15)

print("15 компаний и 15 вакансий успешно созданы!")
